"""实验一 全局配置：目标仓库、AI 信号词典、抓取常量、路径。

该数据集是整门课 7 个实验的共同数据基础，配置集中于此，便于统一调整。
"""
from __future__ import annotations

import os
from pathlib import Path

# --------------------------------------------------------------------------- #
# 路径
# --------------------------------------------------------------------------- #
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"            # 原始 API 缓存：每个 PR 一个 json（可断点续传）
PROCESSED_DIR = DATA_DIR / "processed"  # 清洗后的 5 张表（parquet + csv）
FIGURES_DIR = DATA_DIR / "figures"    # EDA 图表

for _d in (RAW_DIR, PROCESSED_DIR, FIGURES_DIR):
    _d.mkdir(parents=True, exist_ok=True)

# --------------------------------------------------------------------------- #
# GitHub API
# --------------------------------------------------------------------------- #
GITHUB_API = "https://api.github.com"
TOKEN_ENV_VAR = "GITHUB_TOKEN"


def get_token() -> str:
    """从环境（.env 已由调用方 load_dotenv 载入）读取 token。"""
    tok = os.environ.get(TOKEN_ENV_VAR, "").strip()
    if not tok:
        raise RuntimeError(
            f"未找到 {TOKEN_ENV_VAR}。请在项目根目录 .env 中设置 "
            f"{TOKEN_ENV_VAR}=<你的 GitHub token>。"
        )
    return tok


# --------------------------------------------------------------------------- #
# 目标仓库（Python 为主：便于实验二 AST/CFG 与实验三 Code2Vec/CodeBERT 统一处理）
# --------------------------------------------------------------------------- #
# 选取原则：Python 主导 + PR 量大 + 审查文化重（inline comment 多）+ 有 bot/AI 活动。
# 同时覆盖不同社区（Web / 数据科学 / ML / 基础设施 / IoT），呼应实验一拓展目标。
REPOS: list[str] = [
    "django/django",             # Web 框架，审查规范、讨论充分
    "pandas-dev/pandas",         # 数据科学，inline comment 密集
    "huggingface/transformers",  # ML，PR 量大、活跃
    "apache/airflow",            # 基础设施，CI/bot 生态活跃
    "home-assistant/core",       # IoT，PR 吞吐量极高、样本充足
]

# 每仓库抓取的“基础”已关闭 PR 数量。
# 只取 closed（merged 或 unmerged）→ Merge Prediction 标签天然干净（开放 PR 标签未知，排除）。
PRS_PER_REPO = 300

# AI 定向补采：在基础样本之外，针对 AI 信号额外抓取的 PR 上限（每仓库）。
# 目的：保证实验五有足量 AI 生成代码 / AI reviewer 样本（这类 PR 天然稀少）。
AI_OVERSAMPLE_PER_REPO = 50

# --------------------------------------------------------------------------- #
# 限流 / 重试
# --------------------------------------------------------------------------- #
REQUEST_TIMEOUT = 30          # 单请求超时（秒）
MAX_RETRIES = 5               # 单请求最大重试次数
RETRY_BACKOFF_BASE = 2.0      # 指数退避基数（秒）
# 触发二级限流(secondary rate limit)/临近核心限额时的保护性休眠
RATE_LIMIT_SLEEP_BUFFER = 5   # 限额耗尽时，在 reset 时间基础上多等的秒数

# --------------------------------------------------------------------------- #
# AI 信号词典（启发式判定，会记录命中的具体信号，便于人工复核）
# --------------------------------------------------------------------------- #
# 已知“AI 代码审查”机器人账号（判定 has_ai_reviewer）。login 统一小写比较。
AI_REVIEWER_BOTS: set[str] = {
    "coderabbitai[bot]",
    "coderabbitai",
    "sourcery-ai[bot]",
    "sourcery-ai",
    "ellipsis-dev[bot]",
    "ellipsis-dev",
    "codium-ai[bot]",
    "codiumai[bot]",
    "korbit-ai[bot]",
    "pr-agent[bot]",
    "qodo-merge-pro[bot]",
    "gemini-code-assist[bot]",
    "copilot-pull-request-reviewer[bot]",
    "github-copilot[bot]",
    "sweep-ai[bot]",
    "codeant-ai[bot]",
    "greptileai[bot]",
    "bito-code-review[bot]",
}

# 判定 is_ai_code 的文本信号（在 commit message / PR body / co-author 中匹配，忽略大小写）。
# 主要靠 "Co-authored-by: <AI 工具>" 这种强信号，弱信号（body 提及）单独标注、可人工复核。
AI_CODE_COAUTHOR_PATTERNS: list[str] = [
    "co-authored-by: copilot",
    "co-authored-by: github copilot",
    "co-authored-by: cursor",
    "co-authored-by: claude",
    "co-authored-by: chatgpt",
    "co-authored-by: devin",
    "co-authored-by: codegen",
]

# 弱信号：PR body / title 中提及 AI 生成工具（单独记录，作为参考而非强判定）。
AI_CODE_TEXT_HINTS: list[str] = [
    "generated by copilot",
    "generated with copilot",
    "written by claude",
    "generated by chatgpt",
    "generated with cursor",
    "ai-generated",
    "ai generated code",
    "使用 copilot 生成",
    "由 ai 生成",
]

# 已知“代码生成型” bot 作者（PR 由 AI agent 直接开的，视为强 AI 代码信号）。
AI_CODE_AUTHOR_BOTS: set[str] = {
    "devin-ai-integration[bot]",
    "sweep-ai[bot]",
    "codegen-sh[bot]",
    "cursor[bot]",
    "copilot-swe-agent[bot]",
}

# 用于 search API 定向补采的查询片段（配合 repo: 限定）。
AI_SEARCH_QUERIES: list[str] = [
    "copilot in:body",
    "cursor in:body",
    '"co-authored-by: claude" in:body',
    "coderabbit in:comments",
]
